---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning =FALSE, echo= FALSE)

```

Sao Paulo food distribution by Dlaivison R. Silva
========================================================
> The Objective of this exploration is to identify Sao Paulo market for foods and distribution
based on the information provided by openstreetmap.org

```{r echo=FALSE, message=FALSE, warning=FALSE, packages}



library(ggplot2)
library(ggmap)
library(maptools)
library(maps)
library(stringr)
library(dplyr)
library(gridExtra)
library(jsonlite)
library(OpenStreetMap)
library(rgdal)

```

```{r echo=FALSE, message=FALSE, warning=FALSE, Load_the_Data}
# Load the Data

dados <-fromJSON("saopaulo.osm.json", flatten=TRUE)
colnames(dados)



#Filtering the 1st stage to only keep food places

food_places <- subset(dados,(dados$Business=="restaurant" | dados$Business=="cafe" | dados$Business=="fast_food"))



# Local distribuition of food places

 ggplot(data=food_places, aes(food_places$Business)) + geom_histogram(stat='count',colour='black', fill='blue') + xlab("Number of food places in Sao Paulo central area")
 

# location of the food places in Sao Paulo Map

location_food_places <- data.frame(food_places$Name,food_places$Business,food_places$latitude,food_places$Longitude)

xy <- dataframe(location_food_places$latitude,location_food_places$longitude)
map <- openmap(c(-23.4518,-46.8195),c(-23.6718,-46.4260))
plot(map,raster=TRUE)


# Restaurant concentration per street in Sao Paulo


ggplot(data=food_places, aes(food_places$address.street)) + geom_histogram(stat='count',colour='black', fill='blue') + xlab("Concentration per street") + coord_flip()
 


 
  





```


   
